### ISSUE TITLE
Add a task allowing to trigger an Airflow DAG run and wait for its completion

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-airflow#2]
### Feature description

Here is the suggested syntax for the task:
```yaml
id: airflow
namespace: company.team

tasks:
  - id: run_dag
    type: io.kestra.plugin.airflow.dags.TriggerDagRun
    host: http://localhost:8080
    dag: example_astronauts
    wait: true
    checkFrequency: # same as in the io.kestra.plugin.core.flow.WaitFor task
      interval: PT30S # check every 30 seconds by default
    options: # same as in the o.kestra.plugin.core.http.Request task
      basicAuthUser: admin
      basicAuthPassword: admin
    headers:  # same as in the io.kestra.plugin.core.http.Request task
      authorization: 'Bearer <TOKEN>'
    body: # same as in the io.kestra.plugin.core.http.Request task — allow optionally to override the default conf payload sent to the API request
```

The implementation should be functionally equivalent to this blueprint https://kestra.io/blueprints/api/236-trigger-an-apache-airflow-dag-run-from-kestra-and-wait-for-its-completion 

I recommend using this CLI to spin up Airflow for testing https://www.astronomer.io/docs/astro/cli/get-started-cli 

## Important aspects for the implementation:

1. The task can leverage the `io.kestra.plugin.core.http.Request task` task as a basis —  best to use `options` and `headers` to avoid reinventing the wheel for the REST API authentication 
2. Use checkFrequency from the `io.kestra.plugin.core.flow.WaitFor` task for the polling implementation.
3. Set all sensible defaults, including adding kestra-specific metadata to the API call triggering an Airflow DAG, as shown in the blueprint:
```yaml
    body: |
      {
        "conf": {
          "source": "kestra", 
          "flow": "{{ flow.id }}",
          "namespace": "{{ flow.namespace }}",
          "task": "{{ task.id }}",
          "execution": "{{ execution.id }}"
          }
      }
```

This conf is displayed in the DAG run and is helpful for tracking: 
![image](https://github.com/user-attachments/assets/b123b00e-1f81-42e5-9dfb-610e17520440)

**Comment by anna-geller** [comment]
@iNikitaGricenko follow-up before closing the issue:
1. icon is missing on the task
2. the `body` property must be dynamic, currently the Pebble expressions are not rendered, see below

```yaml
id: airflow
namespace: company.team

tasks:
  - id: run_dag
    type: io.kestra.plugin.airflow.dags.TriggerDagRun
    baseUrl: http://host.docker.internal:8080
    dagId: example_astronauts
    wait: true
    pollFrequency: PT1S 
    options: 
      basicAuthUser: admin
      basicAuthPassword: admin
    body: 
      conf:
        source: kestra
        flow: "{{ flow.id }}"
        namespace: "{{ flow.namespace }}"
        task: "{{ task.id }}"
        execution: "{{ execution.id }}"
```

![image](https://github.com/user-attachments/assets/ef52b374-e952-4280-b744-2274d8b3c89a)
